### ISSUE TITLE
testSuite option is ignored

### ISSUE THREAD

**Issue by adiachenko** [mikeerickson/gulp-phpunit#30]
This will not work:
```
// phpunit.xml
<testsuite name="Integration">
    <directory>./tests/Integration/</directory>
</testsuite>
```
```
// gulpfile.js
gulp.task('phpunit:integration', function() {
  gulp.src('phpunit.xml').pipe(phpunit('', {
    testSuite: 'Integration',
  }));
});
```
The gulp task above should be roughly equal to executing `phpunit --testsuite Integration` in the project root when in fact it is not.

I skimmed your code in search of solution and found possible source of the issue. See index.js:189,192
```
if ((opt.testSuite) && (! skip)) {
    cmd += ' ' + opt.testSuite;
    skip = true;
}
```
First of all, you never prepend `--testsuite` flag to the value of opt.testSuite property. It will be passed to exec() as it is and evaluated as raw argument rather than the value of given option.

Secondly, the condition above will never evaluate to true because of `skip` variable check. When reading `phpunit.xml` skip will set to true therefore invalidating this condition.

**Comment by mikeerickson** [comment]
Thx for report, I will have a look and get this resolved.

**Comment by lukewaite** [comment]
I believe this is addressed in https://github.com/mikeerickson/gulp-phpunit/pull/20

**Comment by mikeerickson** [comment]
Fixed in 0.10.x release

**Comment by lukewaite** [comment]
I believe this issue still exists, while 2323c34b fixes the actual call to phpunit it does not address the second half of the issue from the original bug:
> Secondly, the condition above will never evaluate to true because of skip variable check. When reading phpunit.xml skip will set to true therefore invalidating this condition.

In short, if you specify a `phpunit.xml`, `skip` is set to `true` so a setting of `testSuite` has no result.

**Comment by mikeerickson** [comment]
@lukewaite would you mind sharing your gulp task. I will take a look tomorrow and get a fix out for you

**Comment by lukewaite** [comment]
@mikeerickson sorry, I've run out of time tonight. I'll try to get a sample to you tomorrow, and whenever you have time to evaluate that is great. Thanks!

**Comment by mikeerickson** [comment]
@lukewaite sounds good, I will be working on this project over weekend and will get it figured out

**Comment by lukewaite** [comment]
@mikeerickson Thanks! Here's a repo with two branches that should give you an idea of our use case.

https://github.com/lukewaite/gulp-phpunit-sample

Hopefully that's clear, but if not let me know.

**Comment by mikeerickson** [comment]
@lukewaite That is perfect, I will get it figured out before end of weekend.

**Comment by mikeerickson** [comment]
OK, this is actually working in the latest build 0.10.1

If you add 'noConfiguration': true 

The tests will run appropriately

Here is the way I am using it in my test

gulp.task('unit', function() {
  gulp.src('phpunit.xml')
    .pipe(phpunit('', { testSuite: 'Unit', noConfiguration: true, notify: true }))
      .on('error', handleErrors);
});

gulp.task('functional', function() {
  gulp.src('phpunit.xml')
    .pipe(phpunit('', { testSuite: 'Functional', noConfiguration: true, notify: true }))
      .on('error', handleErrors);
});

**Comment by mikeerickson** [comment]
@lukewaite May sure you are using 0.10.1

**Comment by mikeerickson** [comment]
@lukewaite I have completely refactored the internals of gulp-phpunit and this issue should be all clean now.  Just posted version 0.11.0

**Comment by lukewaite** [comment]
Thanks @mikeerickson - sorry for the delay - I'm still in catchup mode from an extended holiday break. I'll give v0.11.0 a shot.

**Comment by mikeerickson** [comment]
Up to 0.11.3 now so make sure to install latest 

$ npm install gulp-phpunit@latest

**Comment by bdjnk** [comment]
@mikeerickson This is still wrong. The `testSuite` option is used only when `noConfiguration: true` (or the config file is not xml), which is strange considering testsuites are defined in xml config files according to [the phpunit docs](https://phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.xml-configuration).

**Comment by mikeerickson** [comment]
@bdjnk Would you mind sending me a clip of your gulp script.   So far as I can tell, it is doing what it should be, but I may be testing a different method than you are doing.

Thx

**Comment by bdjnk** [comment]
First, here's the basic command: `phpunit -c tests/tests.xml --testsuite Model`.

The works correctly in conjunction with tests.xml where I have:

```
<testsuites>
  <testsuite name="Model">
    <directory suffix="test.php">...</directory>
    ...
  </testsuite>
</testsuites>
```

Unfortunately I am unable to achieve that in my gulpfile. Here's the simplest case:

```
gulp.task('phpunit', function() {
	gulp.src('tests/tests.xml')
		.pipe(phpunit('phpunit', {
			testSuite: 'Model',
		}));
});
```

The testSuite gets ignored and is not appended to the final command.

**Comment by teseo** [comment]
Still failing :(

**Comment by teseo** [comment]
Doing a bit of debugging I could see, in my case, the reason why testSuite (and pretty much anything that is wrapped in an if statement with `(! skip)` in it.

in the file `index.js` in the line 188 we can see this code:
```
if ((file.path) && (! skip) && (!opt.noConfiguration)){
    var ext = file.path.substr(file.path.lastIndexOf('.')+1);
    if ( ext === 'xml') {
        cmd += ' -c "' + file.path + '"'; skip = true;
    }
}
```

In my case as i'm using a phpunit.xml file, I do enter inside of that if. The case of the TestSuite option, we can see this if:

```
if ((opt.testSuite) && (! skip)) 
```

As the `skip` variable is set to true, it won't enter the if and ignore completely the testSuite option.

Is this an expected behaviour?
